version: '3.8'

services:
  # MySQL Database Service
  demo-cart-mysql:
    image: mysql:8.0
    container_name: demo-cart-mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: demo-cart
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "8061:3306"  # Mapping MySQL container port 3306 to host port 3320
    volumes:
      - demo-cart-mysql_data:/var/lib/mysql
    networks:
      - demo-cart

  # phpMyAdmin Service for MySQL Management
  demo-cart-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: ecommerce-phpmyadmin-container
    environment:
      PMA_HOST: demo-cart-mysql
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - "8062:80"  # Custom port for phpMyAdmin
    networks:
      - demo-cart

volumes:
  demo-cart-mysql_data:

networks:
  demo-cart:
    driver: bridge
